### ISSUE TITLE
Update Cambria formula to use v5.24 from PCLinuxOS (was: Cambria from `PowerPointViewer.exe` does not support U+2009 "thin space")

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#108]
As described in https://github.com/CalConnect/csd-transcription-systems/issues/94#issuecomment-937637492

Occasionally we see the `#` shown in rendering through Fontist installs of Cambria:
![image](https://user-images.githubusercontent.com/11865/136366923-87f82ea7-dc67-461e-b52c-d5a3e3fe8bd5.png)

The reason is that the Cambria installed from PowerPointViewer.exe does not contain U+2009:
![image](https://user-images.githubusercontent.com/11865/136366809-a3882c27-56a2-4f5d-8fa1-cc0b03ac312e.png)

(font version is 1.02, 2016 vs. 5.97 2009 locally installed)

The normal Cambria installed via Office is of a newer version and contains the thin space.

Perhaps there is another openly installable Cambria that is a newer version with the thin space.

**Comment by ronaldtse** [comment]
From @intelligent2013

> 5.97 2009 from Windows 7 (C:\Windows\Fonts\cambria.ttc):
![image](https://user-images.githubusercontent.com/11865/136371013-6ace9dbd-f832-423b-a123-e6e9b11deecd.png)

> Please note, that there isn't `X` mark across glyph box in this version.

**Comment by ronaldtse** [comment]
I found a Cambria version 5.24 that contains 0x2009 from the PCLinuxOS base distribution.

<img width="253" alt="Screenshot 2022-04-03 at 1 15 58 PM" src="https://user-images.githubusercontent.com/11865/161412787-f5878aeb-9cac-4ec2-a986-e95b31127f0a.png">

These are the package links. Although there are 3 versions of this package, the version of the Cambria font is identical, at 5.24.



`webcore-fonts-1.3-3pclos2009.noarch.rpm`:
* Original: http://kde3.pclosusers.com/RPMS.nonfree/webcore-fonts-1.3-3pclos2009.noarch.rpm
  * Archived: https://web.archive.org/web/20220403050550/http://kde3.pclosusers.com/RPMS.nonfree/webcore-fonts-1.3-3pclos2009.noarch.rpm

* Original: https://ftp.sjtu.edu.cn/sites/www.pclinuxos.com/pclinuxos/pclosfiles/pclinuxos/2010/RPMS.nonfree/webcore-fonts-1.3-3pclos2009.noarch.rpm
  * Archive: https://web.archive.org/web/20220403045355/https://ftp.sjtu.edu.cn/sites/www.pclinuxos.com/pclinuxos/pclosfiles/pclinuxos/2010/RPMS.nonfree/webcore-fonts-1.3-3pclos2009.noarch.rpm

`webcore-fonts-1.3-3pclos2011.src.rpm`:

* Original: https://ftp.sjtu.edu.cn/sites/www.pclinuxos.com/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-3pclos2011.src.rpm
  * Archived: https://web.archive.org/web/20220403050503/https://ftp.sjtu.edu.cn/sites/www.pclinuxos.com/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-3pclos2011.src.rpm

`webcore-fonts-1.3-4pclos2017.src.rpm`: (use this URL order)

* Original: http://mirror.math.princeton.edu/pub/pclinuxos/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archive: https://web.archive.org/web/20220403052754/http://mirror.math.princeton.edu/pub/pclinuxos/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

* Original: http://ftp.jaist.ac.jp/pub/Linux/PCLinuxOS/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archive: https://web.archive.org/web/20220403052808/http://ftp.jaist.ac.jp/pub/Linux/PCLinuxOS/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

* Original: https://ftp.sjtu.edu.cn/sites/www.pclinuxos.com/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archived: https://web.archive.org/web/20220403051221/https://ftp.sjtu.edu.cn/sites/www.pclinuxos.com/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

* Original: https://mirrors.uni-ruse.bg/pclinuxos/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archived: https://web.archive.org/web/20220405035318/https://mirrors.uni-ruse.bg/pclinuxos/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

* Original: http://ftp.klid.dk/ftp/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archived: https://web.archive.org/web/20220403052851/http://ftp.klid.dk/ftp/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

* Original: http://openvz.mirror.garr.it/mirrors/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archived: https://web.archive.org/web/20220403052913/http://openvz.mirror.garr.it/mirrors/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

* Original: https://archive.ubuntulinux.jp/pub/Linux/PCLinuxOS/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archived: https://web.archive.org/web/20220405050546/https://archive.ubuntulinux.jp/pub/Linux/PCLinuxOS/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

* Original: http://distrib-coffee.ipsl.jussieu.fr/pub/linux/pclinuxos/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm
  * Archived: https://web.archive.org/web/20220403052805/http://distrib-coffee.ipsl.jussieu.fr/pub/linux/pclinuxos/pclinuxos/srpms/SRPMS.pclos/webcore-fonts-1.3-4pclos2017.src.rpm

**Comment by ronaldtse** [comment]
This new webcore-fonts set has the following fonts/versions:
```
Andale Mono: 2.00
Arial: 2.95
Arial: 2.90
Arial: 2.90
Arial: 2.90
Arial Black: 2.35
Calibri: 5.62
Calibri: 5.62
Calibri: 5.62
Calibri: 5.62
Cambria: 5.24
Cambria: 5.24
Cambria: 5.24
Comic Sans MS: 2.10
Comic Sans MS: 2.10
Courier New: 2.90
Courier New: 2.90
Courier New: 2.90
Courier New: 2.90
Georgia: 2.11
Georgia: 2.10
Georgia: 2.10
Georgia: 2.10
Impact: 2.35
Lucida Sans Unicode: 2.00
Lucida Console: 1.60
Microsoft Sans Serif: 1.33
Segoe UI: 5.01
Segoe UI: 5.01
Segoe UI Light: 0.90
Segoe UI: 5.01
Segoe UI: 0.70
Segoe UI Semibold: 0.90
Symbol: 1.60
Tahoma: 3.00
Tahoma: 3.00
Times New Roman: 2.95
Times New Roman: 2.90
Times New Roman: 2.90
Times New Roman: 2.90
Trebuchet MS: 1.22
Trebuchet MS: 1.22
Trebuchet MS: 1.22
Trebuchet MS: 1.22
Verdana: 2.41
Verdana: 2.40
Verdana: 2.40
Verdana: 2.40
Webdings: 1.03
Wingdings: 2.55
```

I did a compare with the original webcore-fonts package (https://github.com/fontist/formulas/blob/53c96e52b46506340805e82e8f667ef3a042f480/Formulas/webcore.yml), and interestingly, these are the differences:

* This PCLinuxOS package has mostly older fonts except for:
```
Calibri: 5.62 vs 1.02
Cambria: 5.24 vs 1.02
```
* This PCLinuxOS package also does not contain Consolas and Constantia that were provided in the original
* This PCLinuxOS package provides Segoe UI that did not exist in the original package

**Comment by alemorozov** [comment]
Updated. Also Wingdings 2/3 would be missing for Windows and Linux (macOS has them among add-on fonts).

**Comment by ronaldtse** [comment]
@alexeymorozov as mentioned in #120 we don't want to replace the current webcore-fonts package (from OpenSUSE), but add an additional package from PCLinuxOS / "pclos". So we should end up with opensuse-webcore-fonts and pclos-webcore-fonts. Thanks!
