### ISSUE TITLE
Fix Google fonts update

### ISSUE THREAD

**Issue by alemorozov** [fontist/formulas#121]
Currently it does not fail, nor work:

```
bundler: failed to load command: fontist
(/home/runner/work/formulas/formulas/vendor/bundle/ruby/2.6.0/bin/fontist)
/home/runner/work/formulas/formulas/vendor/bundle/ruby/2.6.0/gems/down-5.3.1/lib/down/net_http.rb:339:in `response_error!': 403 Forbidden (Down::ClientError)

/home/runner/.fontist/google/fonts/ofl/radiocanada, 
```

https://github.com/fontist/formulas/runs/5809288860?check_suite_focus=true
Expand "Import new fonts (new API)"

**Comment by ronaldtse** [comment]
Thanks for discovering this.

**Comment by alemorozov** [comment]
It works properly now.

https://github.com/fontist/formulas/runs/6229064452?check_suite_focus=true

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov !
