### ISSUE TITLE
Add Noto CJK "Variable OTC"

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#129]
* Variable OTC Sans: https://github.com/googlefonts/noto-cjk/tree/main/Sans
  * File: https://github.com/googlefonts/noto-cjk/releases/download/Sans2.004/02_NotoSansCJK-TTF-VF.zip
* Variable OTC Serif: https://github.com/googlefonts/noto-cjk/tree/main/Serif#variable-otcs
  * File: https://github.com/googlefonts/noto-cjk/releases/download/Serif2.001/03_NotoSerifCJK-TTF-VF.zip

**Comment by CAMOBAP** [comment]
Merged
