### ISSUE TITLE
Add support for WorldWeatherSymbols/wx_symbols fonts from OGC MetOcean DWG, through MetPy

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#131]
Font name: wx_symbols

Font file: https://github.com/Unidata/MetPy/blob/main/src/metpy/plots/fonts/wx_symbols.ttf

License: https://github.com/Unidata/MetPy/blob/main/src/metpy/plots/fonts/wx_symbols_license.md

Font glyph source: https://github.com/OGCMetOceanDWG/WorldWeatherSymbols

**Comment by ronaldtse** [comment]
Hi @alexeymorozov , could we prioritise this request? Thanks!

**Comment by alemorozov** [comment]
@ronaldtse Yes, the feature is implemented in `excavate`. Formulas support a regular file instead of an archive now.

Will release excavate after merging.

**Comment by CAMOBAP** [comment]
Merged
