### ISSUE TITLE
Add TeX Gyre DejaVu Math

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#168]
https://www.gust.org.pl/projects/e-foundry/tex-gyre-dejavu-math

Licensing
The TeX Gyre DejaVu Math package is licensed under the [GUST Font License (GFL)](https://www.gust.org.pl/projects/licenses), which is a free license, legally equivalent to the [LaTeX Project Public License (LPPL)](http://www.latex-project.org/lppl/), version 1.3c or later.

**Comment by alemorozov** [comment]
Exactly this one was added along with [`TeX Gyre Math`](https://github.com/fontist/formulas/pull/170).

https://github.com/fontist/formulas/blob/8efea93ac24f484a73920c72a605acf063d21969/Formulas/tex_gyre_math.yml#L26

Closing but if necessary a separate formula can be added.
