### ISSUE TITLE
How do the branches and tags work?

### ISSUE THREAD

**Issue by jcbhmr** [fontist/formulas#173]
question from a niave outsider:
- why is the v3 branch the default branch?
- whats the master branch doing when v3 is the default branch?
- why is master branch 160 commits behind v3?
- which branch should i target for prs?

**Comment by ronaldtse** [comment]
The "version" in the branch name indicate the "version of the fontist formula schema".

i.e. all formulas in "v3" branch are using the formula v3 schema.

> * why is the v3 branch the default branch?

The current version of Fontist uses the formula v3 schema.

> * whats the master branch doing when v3 is the default branch?

The `master` branch is used by the oldest version of the Fontist formula schema.

> * why is master branch 160 commits behind v3?

As prior.

> * which branch should i target for prs?

"v3" is the latest one.

The older versions are no longer updated and only kept for backwards compatibility.

**Comment by ronaldtse** [comment]
@alexeymorozov any further comments? Thanks!

**Comment by jcbhmr** [comment]
thanks! you answered my questions ❤️
