### ISSUE TITLE
Noto Serif JP Bold not supported

### ISSUE THREAD

**Issue by opoudjis** [fontist/formulas#206]
https://github.com/metanorma/metanorma-jis/pull/230 has added the fonts

````
          "Noto Serif JP" => nil,
          "Noto Serif JP ExtraLight" => nil,
          "Noto Serif JP Medium" => nil,
          "Noto Serif JP Bold" => nil,
          "Noto Serif JP Black" => nil,
          "Noto Sans JP Thin" => nil,
          "Noto Sans JP Medium" => nil,
````

On my Mac, these are resulting in a crash:

````
[fontist] 'Noto Serif JP Bold' font is not supported. Please report this issue at github.com/metanorma/metanorma/issues to report this issue.
````

fontist update is not making that crash go away.

**Comment by ronaldtse** [comment]
This issue belongs to the formulas repo. Will transfer.

**Comment by ronaldtse** [comment]
"Noto Serif JP Bold" exists as a font in the formula:
https://github.com/fontist/formulas/blob/ffa7239af974204836af07348948a155a41b6bf3/Formulas/google/noto_serif_jp.yml#L19-L40

What this means is if you install "Noto Serif JP", then it comes with both "Noto Serif JP Regular" and "Noto Serif JP Bold".

What Fontist is not allowing is the specification of the `full_name` as the font name to be installed:
https://github.com/fontist/formulas/blob/ffa7239af974204836af07348948a155a41b6bf3/Formulas/google/noto_serif_jp.yml#L23

i.e.
```sh
$ fontist install 'Noto Serif JP Bold'
Font "Noto Serif JP Bold" not found locally.
Font 'Noto Serif JP Bold' not found locally nor available in the Fontist formula repository.
Perhaps it is available at the latest Fontist formula repository.
You can update the formula repository using the command `fontist update` and try again.
```

It actually installs the font with you install the normal one:
```sh
fontist install 'Noto Serif JP'
Font "Noto Serif JP" not found locally.
Installing from formula "google/noto_serif_jp".
Downloading from https://fonts.gstatic.com/s/notoserifjp/v28/xn71YHs72GKoTvER4Gn3b5eMRtWGkp6o7MjQ2bwxOubAILO5wBCU.ttf
Downloading:    7 MiB, 2.78 MiB/s, done.
Downloading from https://fonts.gstatic.com/s/notoserifjp/v28/xn71YHs72GKoTvER4Gn3b5eMRtWGkp6o7MjQ2bzWPebAILO5wBCU.ttf
Downloading:    7 MiB, 3.21 MiB/s, done.
Fonts installed at:
- ~/.fontist/fonts/xn71YHs72GKoTvER4Gn3b5eMRtWGkp6o7MjQ2bwxOubAILO5wBCU.ttf
- ~/.fontist/fonts/xn71YHs72GKoTvER4Gn3b5eMRtWGkp6o7MjQ2bzWPebAILO5wBCU.ttf
```

**Comment by ronaldtse** [comment]
The point is you don't need to specify installation of "Noto Serif JP Bold" to make "Bold" available.

Or do we need the font available in the font manifest?

**Comment by opoudjis** [comment]
Question for @intelligent2013 , since he requested Noto Serif JP. I think you're right.

**Comment by Intelligent2013** [comment]
Answered here https://github.com/metanorma/metanorma-jis/pull/230#issuecomment-2444042213
`Noto Serif JP` is enough. My mistake.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !
