### ISSUE TITLE
Add SimSun, SimHei fonts

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/formulas#58]
For https://github.com/metanorma/metanorma-gb/issues/148.

**Comment by alexeymorozov** [comment]
Relates to #12

**Comment by ronaldtse** [comment]
I can't find the SimHei font in an available license. SimHei is definitely used in the GB title and clause titles. We can replace SimHei using "Microsoft YaHei" (https://github.com/fontist/formulas/blob/b8df7d26e5009e64a4863ac8ed6786d768377a3a/Formulas/microsoft_yahei.yml) for now.

**Comment by ronaldtse** [comment]
And this is the interesting part that can be implemented in fontist/fontist#119: 

If the user requests for a font, and Fontist does not offer it, it could either: 
- if the font is available in the system, provide that font path. This way the application can directly use that font installed in the system.
- if the font is not available in the system (Fontist cannot detect it), it should:
  - provide no path for the font (in strict mode), then the application needs to figure out itself what to do.
  - provide a compatibility font in font path and also the font name (in compatibility mode), then the application can use a similar/compatible font to proceed.

Thoughts @alexeymorozov ?

**Comment by alexeymorozov** [comment]
Sounds interesting!

It would provide a choice for a consumer in case if there is no requested font. Can even mark a compatible font in a response so an application could decide which font to use, and which not in a compatible mode.

**Comment by ronaldtse** [comment]
That's great! I believe we have a common understanding and this can proceed as described 👍

**Comment by ronaldtse** [comment]
I found it -- SimHei and SimSun are provided in the Office 2016 for Mac Preview #78 ! Once #78 is fixed we can close this.

**Comment by ronaldtse** [comment]
@CAMOBAP we're closing this in favor of #78.
