### ISSUE TITLE
Can you also add "MS PGothic"?

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#73]
Can you also add "MS PGothic"? https://bigfontsite.com/download/ms-pgothic.html#download

_Originally posted by @raffaem in https://github.com/fontist/formulas/issues/70#issuecomment-752422687_

**Comment by ronaldtse** [comment]
@raffaem thank you for the suggestion, the link provided however does not seem to provide the fonts legally.

The MS PGothic font is also available here: https://ftp.gwdg.de/pub/linux/misc/suser-jengelh/openSUSE_Tumbleweed/src/microsoft-japanese-fonts-2.31-5.18.src.rpm

However, this package doesn't provide a license, which makes it difficult to incorporate.

**Comment by ronaldtse** [comment]
@raffaem actually a nearly identical font "HGPGothicM" is already available:
https://github.com/fontist/formulas/blob/f00554db219aeef562b2dc6cd9ade329c3d5a05b/Formulas/japanese.yml#L51

The differences between the fonts can be found here:
https://industry.ricoh.com/en/font/true_type_font/

**Comment by raffaem** [comment]
> @raffaem actually a nearly identical font "HGPGothicM" is already available:
> 
> https://github.com/fontist/formulas/blob/f00554db219aeef562b2dc6cd9ade329c3d5a05b/Formulas/japanese.yml#L51
> 
> The differences between the fonts can be found here:
> https://industry.ricoh.com/en/font/true_type_font/

Hello,

is this font metric-compatible with "MS PGothic" and registered as "MS PGothic"?

If it does not get registered as "MS PGothic", LibreOffice / WPS Office will not use it in lieu of "MS PGothic".

If it is not metric-compatible, the layout will be messed up

Best

**Comment by ronaldtse** [comment]
"MS PGothic" is available directly from the Office 2011 for Mac trial:
https://www.heidoc.net/joomla/technology-science/microsoft/61-office-2011-for-mac-direct-download-links
<img width="576" alt="Screen Shot 2021-01-14 at 2 50 28 PM" src="https://user-images.githubusercontent.com/11865/104554879-d9cb2c00-5677-11eb-81ef-83bc64ef1bb6.png">

It is possible to extract them via:
- `MicrosoftOffice2011.dmg` => extract DMG, contains `Office Installer.pkg`
- `Office Installer.pkg` => extract, contains `Office2011_all_fonts_14.7.7.pkg`
- `Office2011_all_fonts_14.7.7.pkg` contains file `Payload`, which is a ZIP file
- `Payload` contains folder `Library/Fonts/Microsoft` which contains all fonts

<img width="322" alt="Screen Shot 2021-01-14 at 2 54 11 PM" src="https://user-images.githubusercontent.com/11865/104555171-5d851880-5678-11eb-9e34-b767c3b5598a.png">

<img width="143" alt="Screen Shot 2021-01-14 at 2 54 50 PM" src="https://user-images.githubusercontent.com/11865/104555220-74c40600-5678-11eb-910b-02be836692d1.png">

@alexeymorozov is this type of extraction doable?

In any case, this means that these fonts are distributed under the Office 2011 license for the trial.

**Comment by raffaem** [comment]
It's incredible the effort you put into this

Thank you so much

**Comment by ronaldtse** [comment]
Instead of Office 2011 trials, #78 would be a much better choice due to the open license. Let's do that instead.

**Comment by ronaldtse** [comment]
Once we confirm #78 is completed and "MS PGothic" is available as a Formula, we can close this issue. Thanks!

**Comment by alemorozov** [comment]
Restored the Office Preview formula.

It was [removed](https://github.com/fontist/formulas/commit/808f79c0af43d9d05be0683060bae4d1fe72dbb3) because it was used to install some often-used font (afaik, Cambria) but it required an upgraded fontist, so it failed at CI. The `v3` formulas branch requires an upgraded fontist, so it's fine now.

More than that, this formula is avoided by default, because fontist avoids formulas larger than 300 MB (unless it's cached), and the office preview formula is 700 MB. At the same time it can be installed with a special flag, like `--size-limit`, or by a formula name:

```
fontist install -F office_preview
```

**Comment by alemorozov** [comment]
```
fontist update
```

And "MS PGothic" can be installed now:

```
fontist install "MS PGothic"
```

**Comment by ronaldtse** [comment]
@alexeymorozov that’s great! Could you also help add a blog post on the website?

**Comment by alemorozov** [comment]
@ronaldtse Of course! I'll make a PR with the post.

**Comment by ronaldtse** [comment]
And FYI @raffaem this ticket is finally resolved, and "MS PGothic" is now available. Thanks!
