### ISSUE TITLE
Add Office 2016 for Mac Preview

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#78]
The "Office 2016 for Mac Preview" is a free download that does not require any subscription (https://techcrunch.com/2015/03/05/office-2016-for-mac-preview-free/). It has a license that does not necessarily restrict font usage, which is good.

Original page:
https://web.archive.org/web/20150507144723/http://products.office.com/en-US/mac/mac-preview

The active "subscription" would have expired in Oct 2015, but the software license does not restrict usage:
https://blogs.office.com/2015/07/22/your-top-10-questions-about-office-2016-for-mac-answered

The original full package is available here (2.66 GB):
http://officecdn.microsoft.com/pr/OfficeMac/OfficePreview.pkg
([archive.org first link](https://web.archive.org/web/20150410232559/http://officecdn.microsoft.com/pr/OfficeMac/OfficePreview.pkg), [archive.org latest](https://web.archive.org/web/20200524160713/http://officecdn.microsoft.com/pr/OfficeMac/OfficePreview.pkg))

Updated in 2015 June:
https://support.microsoft.com/en-us/help/3074179/office-2016-for-mac-preview-june-23-2015-update

Updated files:
Outlook: http://download.microsoft.com/download/C/C/C/CCC09D91-6F8D-42CB-B3B0-CA9667181DE8/Microsoft_Outlook_15.11.1_Updater.pkg ([archive.org link](https://web.archive.org/web/20210122163352/http://download.microsoft.com/download/C/C/C/CCC09D91-6F8D-42CB-B3B0-CA9667181DE8/Microsoft_Outlook_15.11.1_Updater.pkg)) (449MB)
PowerPoint: http://download.microsoft.com/download/7/9/d/79d18a87-4a64-4104-80a7-0917763d6161/microsoft_powerpoint_15.11.1_updater.pkg ([archive.org lihk](https://web.archive.org/web/20210122160650/http://download.microsoft.com/download/7/9/d/79d18a87-4a64-4104-80a7-0917763d6161/microsoft_powerpoint_15.11.1_updater.pkg)) (708MB)
Word: http://download.microsoft.com/download/c/4/9/c498c0fa-f799-4764-b49e-f70b32e7c6cb/microsoft_word_15.11.1_updater.pkg
([archive.org link](https://web.archive.org/web/20150728172102/http://download.microsoft.com/download/c/4/9/c498c0fa-f799-4764-b49e-f70b32e7c6cb/microsoft_word_15.11.1_updater.pkg)) (846MB)
Excel: http://download.microsoft.com/download/8/1/3/8136bf31-4c2e-4b5f-bee9-117ab004ab35/microsoft_excel_15.11.1_updater.pkg ([archive.org link](https://web.archive.org/web/20210122163523/http://download.microsoft.com/download/8/1/3/8136bf31-4c2e-4b5f-bee9-117ab004ab35/microsoft_excel_15.11.1_updater.pkg)) (736MB)

The license (extracted from OfficePreview.pkg) is provided here:
[License.rtf.zip](https://github.com/fontist/formulas/files/5816364/License.rtf.zip)

If we want to work off OfficePreview.pkg (2.66GB, from 2015-06-09), the order is:
- `OfficePreview.pkg `
- contains `Office_fonts.pkg` which is a directory
- contains `Payload` which is a ZIP
- contains `Fonts` which contain all fonts

Here we prefer the Excel version (736MB, from the latest 2015-06-23 update, file date 2015-06-18) because it's smaller and the CDN is a lot faster than the OfficePreview.pkg.
- `microsoft_excel_15.11.1_updater.pkg`
- contains `Microsoft_Excel.pkg` which is a directory
- contains `Payload` which is a ZIP
- contains `Microsoft Excel.app` which is a directory
- contains `Contents/Resources/Fonts` which contain all fonts

The fonts contained in both of these directories are identical in file size and in count.

In particular, this also contains `msgothic.ttc` which contains PGothic as requested in #73 .

Fonts provided:
```
AbadiMTCondensedExtraBold.ttf
AbadiMTCondensedLight.ttf
ArialNarrowBoldItalic.ttf
ArialNarrowItalic.ttf
ArialRoundedMTBold.ttf
BaskervilleOldFace.ttf
Bauhaus93.ttf
BellMT.ttf
BellMTBold.ttf
BellMTItalic.ttf
BernardMTCondensed.ttf
Book Antiqua Bold Italic.ttf
Book Antiqua Bold.ttf
Book Antiqua Italic.ttf
Book Antiqua.ttf
Bookman Old Style Bold Italic.ttf
Bookman Old Style Bold.ttf
Bookman Old Style Italic.ttf
Bookman Old Style.ttf
Bookshelf Symbol 7.ttf
Braggadocio.ttf
BritannicBold.ttf
Calibri.ttf
Calibrib.ttf
Calibrii.ttf
Calibriz.ttf
Calisto MT Bold.ttf
Calisto MT Italic.ttf
Calisto MT.ttf
CalistoMTBoldItalic.ttf
Cambria.ttc
Cambriab.TTF
Cambriai.TTF
Cambriaz.TTF
Candara.ttf
Candarab.ttf
Candarai.ttf
Candaraz.ttf
Century Gothic Bold Italic.ttf
Century Gothic Bold.ttf
Century Gothic Italic.ttf
Century Gothic.ttf
Century Schoolbook Bold Italic.ttf
Century Schoolbook Bold.ttf
Century Schoolbook Italic.ttf
Century Schoolbook.ttf
Century.ttf
ColonnaMT.ttf
ComicSansMSBold.ttf
Consola.ttf
Consolab.ttf
Consolai.ttf
Consolaz.ttf
Constan.TTF
Constanb.TTF
Constani.TTF
Constanz.TTF
Cooper Black
CopperplateGothicBold.ttf
Corbel.ttf
Corbelb.ttf
Corbeli.ttf
Corbelz.ttf
CurlzMT.ttf
Deng.ttf
Dengb.ttf
Dengl.ttf
Desdemona.ttf
EdwardianScriptITC.ttf
EngraversMT.ttf
EngraversMTBold.ttf
Eurostile Bold.ttf
Eurostile.ttf
Fangsong.ttf
FootlightMTLight.ttf
Franklin Gothic Book Italic.ttf
Franklin Gothic Book.ttf
Franklin Gothic Demi Cond.ttf
Franklin Gothic Demi Italic.ttf
Franklin Gothic Demi.ttf
Franklin Gothic Heavy Italic.ttf
Franklin Gothic Heavy.ttf
Franklin Gothic Medium Cond.ttf
Franklin Gothic Medium Italic.ttf
Franklin Gothic Medium.ttf
GARA.TTF
GARABD.TTF
GARAIT.TTF
Gabriola.ttf
Gill Sans MT Bold Italic.ttf
Gill Sans MT Bold.ttf
Gill Sans MT Condensed.ttf
Gill Sans MT Ext Condensed Bold.ttf
Gill Sans MT Italic.ttf
Gill Sans MT.ttf
GillSansUltraBold.ttf
GloucesterMTExtraCondensed.ttf
Goudy Old Style Bold.ttf
Goudy Old Style Italic.ttf
Goudy Old Style.ttf
HGRGE.ttc
HGRME.ttc
HGRSGU.ttc
HGRSMP.TTF
Haettenschweiler.ttf
Harrington.ttf
ImprintMTShadow.ttf
Kaiti.ttf
KinoMT.ttf
Lucida Console.ttf
Lucida Sans Demibold Italic.ttf
Lucida Sans Demibold Roman.ttf
Lucida Sans Italic.ttf
Lucida Sans Unicode.ttf
Lucida Sans.ttf
LucidaBlackletter.ttf
LucidaBright.ttf
LucidaBrightDemibold.ttf
LucidaBrightDemiboldItalic.ttf
LucidaBrightItalic.ttf
LucidaCalligraphyItalic.ttf
LucidaFaxDemibold.ttf
LucidaFaxDemiboldItalic.ttf
LucidaFaxItalic.ttf
LucidaFaxRegular.ttf
LucidaHandwritingItalic.ttf
LucidaSansTypewriterBold.ttf
LucidaSansTypewriterBoldOblique.ttf
LucidaSansTypewriterOblique.ttf
LucidaSansTypewriterRegular.ttf
MS Reference Sans Serif.ttf
MS Reference Specialty.ttf
MSJH.ttf
MSJHBD.ttf
MTEXTRA.TTF
Marlett.ttf
MaturaMTScriptCapitals.ttf
Meiryo.ttf
MeiryoBold.ttf
MeiryoBoldItalic.ttf
MeiryoItalic.ttf
Mistral.ttf
ModernNo.20.ttf
MonotypeCorsiva.ttf
MonotypeSorts.ttf
News Gothic MT Bold Italic.ttf
News Gothic MT Bold.ttf
News Gothic MT Italic.ttf
News Gothic MT.ttf
Onyx.ttf
Perpetua Bold Italic.ttf
Perpetua Bold.ttf
Perpetua Italic.ttf
Perpetua Titling MT Bold.ttf
Perpetua Titling MT.ttf
Perpetua.ttf
Rockwell Bold Italic.ttf
Rockwell Bold.ttf
Rockwell Condensed Bold.ttf
Rockwell Condensed.ttf
Rockwell Extra Bold.ttf
Rockwell Italic.ttf
Rockwell.ttf
STHUPO.TTF
STLITI.ttf
STXINGKA.ttf
STXINWEI.ttf
STZHONGS.ttf
Segoe Print Bold.ttf
Segoe Script Bold.ttf
SimHei.ttf
SimSun.ttf
Stencil.ttf
TaiLeb.ttf
TrebuchetMSBoldItalic.ttf
Tw Cen MT Bold Italic.ttf
Tw Cen MT Bold.ttf
Tw Cen MT Condensed Bold.ttf
Tw Cen MT Condensed Extra Bold.ttf
Tw Cen MT Condensed.ttf
Tw Cen MT Italic.ttf
Tw Cen MT.ttf
Verdana Bold Italic.ttf
Verdana Bold.ttf
Verdana Italic.ttf
Verdana.ttf
WideLatin.ttf
Wingdings 2.ttf
Wingdings 3.ttf
Wingdings.ttf
YuGothB.ttf
YuGothL.ttf
YuGothM.ttf
YuGothR.ttf
arial.ttf
arialbd.ttf
arialbi.ttf
ariali.ttf
ariblk.ttf
batang.ttc
calibril.ttf
calibrili.ttf
gulim.ttc
himalaya.ttf
malgun.ttf
malgunbd.ttf
malgunsl.ttf
mingliu.ttc
mingliub.ttc
monbaiti.ttf
msgothic.ttc
msmincho.ttc
msyh.ttf
msyhbd.ttf
msyi.ttf
ntailu.ttf
ntailub.ttf
pala.ttf
palab.ttf
palabi.ttf
palai.ttf
simsunb.ttf
tahoma.ttf
tahomabd.ttf
taile.ttf
webdings.ttf
yumin.ttf
```

---------

Full EULA

Office for Mac Privacy Statement 
MICROSOFT SOFTWARE LICENSE TERMS
MICROSOFT OFFICE FOR MAC 
These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
•	updates,
•	supplements,
•	Internet-based services, and
•	support services
for this software, unless other terms accompany those items. If so, those terms apply.
By using the software, you accept these terms. If you do not accept them, do not use the software.
As described below, using some features also operates as your consent to the transmission of certain standard computer information for Internet-based services.
If you comply with these license terms, you have the perpetual rights below.
1.	INSTALLATION AND USE RIGHTS. 
a.	Installation and Use. You may install and use one copy of the software on your device.
b.	Third Party Programs. The software may include third party programs that Microsoft, not the third party, licenses to you under this agreement. Notices, if any, for the third party program are included for your information only.
2.	INTERNET-BASED SERVICES. Microsoft provides Internet-based services with the software. It may change or cancel them at any time. You may not use the service to try to gain unauthorized access to any service, data, account or network by any means.
3.	SCOPE OF LICENSE. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you may use the software only as expressly permitted in this agreement. In doing so, you must comply with any technical limitations in the software that only allow you to use it in certain ways. You may not
•	work around any technical limitations in the software;
•	reverse engineer, decompile or disassemble the software, except and only to the extent that applicable law expressly permits, despite this limitation;
•	make more copies of the software than specified in this agreement or allowed by applicable law, despite this limitation;
•	publish the software for others to copy;
•	rent, lease or lend the software;
•	use the software for commercial software hosting services.
4.	BACKUP COPY. You may make one backup copy of the software. You may use it only to reinstall the software.
5.	DOCUMENTATION. Any person that has valid access to your computer or internal network may copy and use the documentation for your internal, reference purposes.
6.	TRANSFER TO ANOTHER DEVICE. You may uninstall the software and install it on another device for your use. You may not do so to share this license between devices.
7.	EXPORT RESTRICTIONS. The software is subject to United States export laws and regulations. You must comply with all domestic and international export laws and regulations that apply to the software. These laws include restrictions on destinations, end users and end use. For additional information, see www.microsoft.com/exporting.
8.	SUPPORT SERVICES. Because this software is “as is,” we may not provide support services for it.
9.	ENTIRE AGREEMENT. This agreement, and the terms for supplements, updates, Internet-based services and support services that you use, are the entire agreement for the software and support services.
10.	APPLICABLE LAW.
a.	United States. If you acquired the software in the United States, Washington state law governs the interpretation of this agreement and applies to claims for breach of it, regardless of conflict of laws principles. The laws of the state where you live govern all other claims, including claims under state consumer protection laws, unfair competition laws, and in tort.
b.	Outside the United States. If you acquired the software in any other country, the laws of that country apply.
11.	LEGAL EFFECT. This agreement describes certain legal rights. You may have other rights under the laws of your country. You may also have rights with respect to the party from whom you acquired the software. This agreement does not change your rights under the laws of your country if the laws of your country do not permit it to do so.
12.	DISCLAIMER OF WARRANTY. The software is licensed “as-is.” You bear the risk of using it. Microsoft gives no express warranties, guarantees or conditions. You may have additional consumer rights or statutory guarantees under your local laws which this agreement cannot change. To the extent permitted under your local laws, Microsoft excludes the implied warranties of merchantability, fitness for a particular purpose and non-infringement.
FOR AUSTRALIA – You have statutory guarantees under the Australian Consumer Law and nothing in these terms is intended to affect those rights.
13.	LIMITATION ON AND EXCLUSION OF REMEDIES AND DAMAGES. You can recover from Microsoft and its suppliers only direct damages up to U.S. $5.00. You cannot recover any other damages, including consequential, lost profits, special, indirect or incidental damages.
This limitation applies to
•	anything related to the software, services, content (including code) on third party Internet sites, or third party programs; and
•	claims for breach of contract, breach of warranty, guarantee or condition, strict liability, negligence, or other tort to the extent permitted by applicable law.
It also applies even if Microsoft knew or should have known about the possibility of the damages. The above limitation or exclusion may not apply to you because your country may not allow the exclusion or limitation of incidental, consequential or other damages.

**Comment by opoudjis** [comment]
Please address this issue before Monday if possible, it is now disrupting rspec testing of Metanorma

**Comment by ronaldtse** [comment]
Strange - this link http://officecdn.microsoft.com/pr/OfficeMac/OfficePreview.pkg is now returning Bad Request. The archive.org link works well but of course not as fast.

This full package is still available on CNet's Download.com: https://download.cnet.com/Microsoft-Office-2016-Preview/3001-18483_4-10823120.html  , but a real browser seems to be needed to download it.

It seems that the official download pages have suddenly been pulled, but the updater links are still available. In any case, they are all available on archive.org.

NOTE:
- The PowerPoint update package contains all the same fonts as the full preview package and the Word/Excel updaters, except `yumin.ttf`.
- The Outlook update package contains limited fonts (Arial, Calibri, Cambria, Consola, Meiryo, Mingliu, SimSun).
- It would be best to use the Excel updater.

**Comment by ronaldtse** [comment]
Apparently the method of finding fonts is also documented here: https://srad.jp/~GPH/journal/620323/ from 2018

**Comment by ronaldtse** [comment]
The Download.com/CNET link requires a signature, so an additional step is required to obtain the dynamic link from the website.

Steps:
1. https://download.cnet.com/Microsoft-Office-2016-Preview/3001-18483_4-10823120.html
2. https://prod.downloadnow.com/s/14/24/37/76/OfficePreview.pkg?GoogleAccessId=download-sps-prod@i-cmb-prod.iam.gserviceaccount.com&Expires=1611334891&Signature=vNWa%2BIoWji9X5kfe%2BK48FZUZlXE9IMO4U9Fq23C1qpNiu%2FOxIDAfwM1I7%2FHqH4OU0f5AxnuTM4DTjBCRvsQRjKlJVyZkIRa7rfBwB7Vb77f4RCq3PpS%2Bok8wcbfDel7q3ygDoje3BFUU%2FVWI%2FpZVVjXwfHJsOoAqKGyNzGOO386j2CKcwYmIKaMWgjWLegZ82OeI0YBSm0TQVbKYbfL3qYWEjyCmTSpzQkorA6yyvHT9rmu2YGO0LET57aABdnxGolKESCyIY4%2B0o8wOYazvWYZIRCq4f5k0U%2BAmFHfMO4DNgrKnUvaItmWivB43LtXkXyDufYV0jobIb7eL6lSB8Q%3D%3D

**Comment by ronaldtse** [comment]
The archive.org link for the 2.66GB file doesn't work anymore. Only the download.com/CNet link works now.

**Comment by alexeymorozov** [comment]
Have issues extracting `pkg` and `cpio` from the excel package.

I do the following:

1. extract `microsoft_excel_15.11.1_updater.pkg` with `pkgutil`, it works, but could not find cross-platform Ruby solution
2. extract `Payload` with `Zlib`, it's ok
3. the resulting file is a cpio archive (`ASCII cpio archive (pre-SVR4 or odc)`), current cpio unarchiver could not unarchive it, may the old magic format would work

Will continue.

**Comment by ronaldtse** [comment]
Apparently 7zip supports it as per the post below?

more details:
https://stackoverflow.com/questions/11298855/how-to-unpack-and-pack-pkg-file

a parser that can extract the PKG files:
https://github.com/NiklasRosenstein/pbzx

**Comment by alexeymorozov** [comment]
Thanks, Ronald, it helped! :) Prototyped a working solution with [the xar gem](https://rubygems.org/gems/xar). I've done a small fix in the library which is needed to be published before usage but overall it's working.

7z can do it but not the version in [a ruby gem](https://github.com/masamitsu-murase/seven_zip_ruby).

The `pbzx` script could not unpack it because this pkg file contains a plain xar format without a pbzx stream.

**Comment by alexeymorozov** [comment]
The xar gem [needs to be compiled](https://github.com/fontist/fontist/pull/219/checks?check_run_id=1879795625) or libxar to exist in a system :(

Trying to compile it and currently see no other option.

**Comment by alexeymorozov** [comment]
Fixed some issues and compiled xar on MacOS. Will do it with rake-compiler in a forked gem.

**Comment by ronaldtse** [comment]
@alexeymorozov if you need a gem compiled for multiple platforms @CAMOBAP has experience with it, he could do the CI builds/release.

**Comment by alexeymorozov** [comment]
@CAMOBAP, thank you for work in https://github.com/fontist/extract_ttc/issues/3. It was helpful! Asked a question in Skype, please look when you have time.

I'd rather continue the work with some help but, if there are other thoughts, can switch to the next tasks.

Compiled the binary [here](https://github.com/alexeymorozov/ruby-xar/tree/cross-compilation/lib). Currently have [an issue](https://github.com/fontist/fontist/pull/219/checks?check_run_id=1893200727) with a local path to Ruby in a compiled binary. It was taken from a machine on which it was compiled.

**Comment by CAMOBAP** [comment]
@alexeymorozov I will provide PR for https://github.com/alexeymorozov/ruby-xar to compile `libxar` properly

**Comment by alexeymorozov** [comment]
Though `libarchive` has been compiled with no significant problem, seems that it could not extract our pkg/xar archive.

Test files:
- https://github.com/libarchive/libarchive/files/1417353/test.pkg.zip (unzipped)
- https://github.com/fontist/excavate/raw/46a7873554eec95e7caf9975dce5fcea526b3d5c/spec/examples/archives/fonts.pkg

```ruby
require "ffi-libarchive"

path = File.expand_path('test.pkg', __dir__)
flags = Archive::EXTRACT_PERM
reader = Archive::Reader.open_filename(path)

reader.each_entry do |entry|
  reader.extract(entry, flags.to_i)
end

reader.close
```

[C implementation](https://github.com/libarchive/libarchive/blob/master/examples/tarfilter.c) does not work either:

```
curl -O https://raw.githubusercontent.com/libarchive/libarchive/master/examples/tarfilter.c
gcc -I/usr/local/opt/libarchive/include -Wall -o tarfilter tarfilter.c -larchive -lz -lbz2
./tarfilter < test.pkg > ustar.tar
```

Though both implementation work with no problem with "tar.gz" archives.

Have some ideas:

1. Fix it in `libarchive`, can use original https://github.com/mackyle/xar
2. Find another lib
3. Port https://github.com/mackyle/xar to support Windows
4. Provide fontist with already existing executable solutions, like Easy 7-Zip on Windows

**Comment by alexeymorozov** [comment]
Recompiled `tarfilter` linking the latest compiled libarchive, and it worked. The system one is too old and has old bugs. Will continue.

**Comment by alexeymorozov** [comment]
Done.

To use new fonts `excavate` (fontist's dependency) should be updated to v0.2.2.

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov !

**Comment by ronaldtse** [comment]
@alexeymorozov I was just checking #219 but it doesn't seem the corresponding Formula has been created in fontist/formula. This was originally necessary for #73 . Can you help check?

**Comment by ronaldtse** [comment]
> Strange - this link http://officecdn.microsoft.com/pr/OfficeMac/OfficePreview.pkg is now returning Bad Request. The archive.org link works well but of course not as fast.

This link is still working as of now.
