### ISSUE TITLE
macOS downloadable fonts

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#84]
macOS Catalina and Big Sur supports downloading of optional fonts when needed.

According to https://discussions.apple.com/thread/250835565 (and described here), the font URL manifest is located at: `/System/Library/AssetsV2/com_apple_MobileAsset_Font6/com_apple_MobileAsset_Font6.xml`

In this file, it contains a manifest of all macOS dynamically downloadable fonts.

For example, Proxima Nova is available in Catalina/Big Sur:

```xml
		<dict>
			<key>Build</key>
			<string>9M3446</string>
...
			<key>FontDesignLanguages</key>
			<array>
				<string>de</string>
...
			</array>
			<key>FontInfo4</key>
			<array>
				<dict>
					<dict>
						<key>en</key>
						<string>Proxima Nova</string>
					</dict>
					<key>FontFamilyName</key>
					<string>Proxima Nova</string>
					<key>FontStyleName</key>
					<string>Regular</string>
					<key>LocalizedFamilyNames</key>
					<dict>
						<key>en</key>
						<string>Proxima Nova</string>
					</dict>
					<key>LocalizedStyleNames</key>
					<dict>
						<key>en</key>
						<string>Regular</string>
					</dict>
					<key>PostScriptFontName</key>
					<string>ProximaNova-Regular</string>
				</dict>
...
			</dict>
			</array>
...
			<string>zip</string>
			<key>_DownloadSize</key>
			<integer>943095</integer>
			<key>_IsZipStreamable</key>
			<true/>
			<key>_MasteredVersion</key>
			<string>3446</string>
			<key>_Measurement</key>
			<data>
			0N6DQ/ju7aS88aW5HofthZcSOMw=
			</data>
			<key>_MeasurementAlgorithm</key>
			<string>SHA-1</string>
			<key>_UnarchivedSize</key>
			<integer>1622016</integer>
			<key>__BaseURL</key>
			<string>http://updates-http.cdn-apple.com/2020/ios/061-87819-20200306-93DA1D52-6008-11EA-8852-69B153371E3E/</string>
			<key>__CanUseLocalCacheServer</key>
			<true/>
			<key>__RelativePath</key>
			<string>com_apple_MobileAsset_Font6/3d1e8640223ec21a7510c346acd4d3abb45ba24f.zip</string>
		</dict>
```

The full URL just joins `__BaseURL` and `__RelativePath`.

As described [here](https://pxlnv.com/linklog/catalina-hidden-typefaces/):
> However, they appear to be saved as standard TrueType containers, and I don’t see any restrictions on their use for commercial projects in their metadata or the Catalina EULA (PDF)

In the Big Sur version, these fonts should be under the [macOS EULA](https://www.apple.com/legal/sla/docs/macOSBigSur.pdf).

This page https://dslabo.blog.fc2.com/blog-entry-2421.html the list of dynamically downloadable fonts available:
<img width="718" alt="Screen Shot 2021-01-23 at 3 01 45 AM" src="https://user-images.githubusercontent.com/11865/105533616-57053980-5d27-11eb-815f-cb81ea7e8aa4.png">
<img width="711" alt="Screen Shot 2021-01-23 at 3 02 02 AM" src="https://user-images.githubusercontent.com/11865/105533637-608ea180-5d27-11eb-9a63-03ba190b2bc3.png">
<img width="708" alt="Screen Shot 2021-01-23 at 3 02 11 AM" src="https://user-images.githubusercontent.com/11865/105533659-66848280-5d27-11eb-8b04-d0ddf0830422.png">

**Comment by ronaldtse** [comment]
The license contains:

-------

For use on Apple-branded Systems

2. Permitted License Uses and Restrictions.
3. 
A. Preinstalled and Single-Copy Apple Software License. Subject to the terms and conditions of this License, unless you obtained the Apple Software from the Mac App Store, through an automatic download or under a volume license, maintenance or other written agreement from Apple, you are granted a limited, non-exclusive license to install, use and run one (1) copy of the Apple Software on a single Apple-branded computer at any one time. For example, these single-copy license terms apply to you if you obtained the Apple Software preinstalled on Apple-branded hardware.

B. Mac App Store License. If you obtained a license for the Apple Software from the Mac App Store or through an automatic download, then subject to the terms and conditions of this License and as permitted by the Services and Content Usage Rules set forth in the Apple Media Services Terms and Conditions (https://www.apple.com/legal/internet-services/itunes/) (“Usage Rules”), you are granted a limited, non-transferable, non-exclusive license:
(i) to download, install, use and run for personal, non-commercial use, one (1) copy of the Apple Software directly on each Apple-branded computer running macOS Catalina, macOS Mojave, macOS High Sierra, macOS Sierra, OS X El Capitan, OS X Yosemite, OS X Mavericks, OS X Mountain Lion or OS X Lion (“Mac Computer”) that you own or control;
(ii) If you are a commercial enterprise or educational institution, to download, install, use and run one (1) copy of the Apple Software for use either: (a) by a single individual on each of the Mac Computer(s) that you own or control, or (b) by multiple individuals on a single shared Mac Computer that you own or control. For example, a single employee may use the Apple Software on both the employee’s desktop Mac Computer and laptop Mac Computer, or multiple students may serially use the Apple Software on a single Mac Computer located at a resource center or library; and
(iii) to install, use and run up to two (2) additional copies or instances of the Apple Software within virtual operating system environments on each Mac Computer you own or control that is already running the Apple Software, for purposes of: (a) software development; (b) testing during software development; (c) using macOS Server; or (d) personal, non-commercial use.
Except as expressly permitted in Section 3, the grant set forth in Section 2B(iii) above does not permit you to use the virtualized copies or instances of the Apple Software in connection with service bureau, time-sharing, terminal sharing or other similar types of services. Except as expressly permitted in this Section 2B, you may not use the Apple Software to run any Apple operating system software, including iOS, iPadOS, watchOS or tvOS, in virtual operating system environments on Mac Computer(s).

--------

It's unclear what category these fonts drop in to, maybe B since it is an 'automatic download', which means 1 copy per Apple-branded computer.

Similar to #85 maybe it would be a good idea to have some "license" platform detection?

**Comment by ronaldtse** [comment]
@alexeymorozov is this issue complete now? If so please help close it, thanks!

**Comment by alemorozov** [comment]
It's finally done :)

**Comment by ronaldtse** [comment]
Thanks @alexeymorozov !
