### ISSUE TITLE
(URGENT) "webcore" font location at opensuse.org now fails due to updated version and rename

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#99]
```
Downloading font "webcore" from https://download.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm
2444
/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/fontist-1.11.1/lib/fontist/utils/downloader.rb:84:in `rescue in download_file': Invalid URL: https://download.opensuse.org/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm (Fontist::Errors::InvalidResourceError)
2445
```

We need to do something with these constant version updates.

**Comment by ronaldtse** [comment]
https://software.opensuse.org/download/package?package=webcore-fonts-vista&project=home%3Aalteratio%3ACommon

<img width="1105" alt="Screenshot 2021-08-30 at 5 45 05 PM" src="https://user-images.githubusercontent.com/11865/131320630-67e7e18f-79b8-4de4-b111-4c2aa44a83aa.png">

Maybe we should switch to a more stable mirror:
http://rpm.pbone.net/results_srodzaj_3_search_webcore-fonts.html

**Comment by alemorozov** [comment]
Fontist still doesn't support retries for downloading and doesn't iterate over mirrors. Currently it only uses the first url one time, and if it fails, fontist stops. Let's add retries and iteration over mirrors?

Urls from the links above seems that don't contain fonts (should be the src version?), or I missed something. So temporarily I've changed it to another our mirror.

The current mirror `download.opensuse.org` fails occasionally, doesn't it?

**Comment by alemorozov** [comment]
@ronaldtse I can add retries and iterate over mirrors, what do you think?

**Comment by ronaldtse** [comment]
@alexeymorozov agree with this. Let's make the enhancement. Thanks!
